name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  markdown-components:
    name: markdown-modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: scilus/nf-neuro
          ref: main
          path: nf-neuro
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10"
          cache: pip
      - name: Install dependencies
        run: |
          pip install pyyaml
      - name: Generate markdown
        id: generate-module
        run: |
          mkdir -p modules/ subworkflows/
          python nf-neuro/docs/astro/convert_modules.yml nf-neuro/modules/nf-neuro modules/
          python nf-neuro/docs/astro/convert_subworkflows.yml nf-neuro/subworkflows/nf-neuro subworkflows/
      - name: Pack into artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: |
            modules/
            subworkflows/

  build:
    needs: markdown-components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website code
        uses: actions/checkout@v4
        with:
          repository: AlexVCaron/nf-neuro-documentation

      - name: Download components markdown
        uses: actions/download-artifact@v4
        with:
          name: markdown
          path: src/content/docs/

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          node-version: 22
          package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
